[all]
node1 ansible_host=10.1.20.11
node2 ansible_host=10.1.20.12
node3 ansible_host=10.1.20.13
;node4 ansible_host=10.1.20.14
node5 ansible_host=10.1.20.15
;node6 ansible_host=10.1.20.16

[masters]
node1
node2

[workers]
node3
;node4
node5
;node6

[k3s_cluster:children]
masters
workers

[all:vars]
ansible_user=fleetadmin
ansible_ssh_pass=fleetadmin
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o userknownhostsfile=/dev/null'
ansible_python_interpreter=auto_silent
