service:
  type: NodePort

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
    nodePort: 30080
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP
    nodePort: 30443

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

logs:
  access:
    enabled: true
