service:
  type: NodePort

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
    nodePort: 30080
    redirectTo:
      port: websecure
      permanent: true
  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP
    nodePort: 30443
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

logs:
  access:
    enabled: true
