persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain

defaultSettings:
  defaultReplicaCount: 2
  defaultDataPath: /var/lib/longhorn
  replicaSoftAntiAffinity: true
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 10
  upgradeChecker: false
  autoSalvage: true
  disableSchedulingOnCordonedNode: true
  replicaZoneSoftAntiAffinity: true

csi:
  attacherReplicaCount: 3
  provisionerReplicaCount: 3
  resizerReplicaCount: 3
  snapshotterReplicaCount: 3

metrics:
  serviceMonitor:
    enabled: true
